app/models/item.rb, app/models/trip.rb, app/models/trip_item.rb, db/migrate/20191118093849_create_trips.rb, db/migrate/20191118094125_create_items.rb, db/migrate/20191118094442_create_trip_items.rb, db/schema.rb, db/seeds.rb, test/models/item_test.rb, test/models/trip_item_test.rb, test/models/trip_test.rb
=> done with seeds and models

app/controllers/items_controller.rb, app/controllers/trip_items_controller.rb, app/controllers/trips_controller.rb, app/models/item.rb, app/models/trip.rb, app/models/user.rb, app/views/trip_items/edit.html.erb, app/views/trips/new.html.erb, app/views/trips/show.html.erb, config/routes.rb, test/controllers/items_controller_test.rb, test/controllers/trip_items_controller_test.rb, test/controllers/trips_controller_test.rb
Created controllers, views and routes
=> Created controllers, views and routes

.gitignore, Gemfile, Gemfile.lock, app/models/item.rb, app/uploaders/photo_uploader.rb
=> Added details for cloudinary

db/seeds.rb
Please approve this pull request
=> Seeds creation

Gemfile, Gemfile.lock, app/controllers/items_controller.rb, app/models/item.rb, app/views/items/new.html.erb, db/migrate/20191119055226_add_photo_to_items.rb, db/schema.rb
Added migration for photo to item
=> Added migration for photo to item

app/models/item.rb, app/views/items/index.html.erb, db/seeds.rb
Structure of cards on the items index page
=> Structure of cards on the items index page

app/views/items/index.html.erb, db/schema.rb, package.json
Added missing comma in package.json
=> Added missing comma in package.json

app/controllers/application_controller.rb, app/controllers/pages_controller.rb, app/models/user.rb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/pages/home.html.erb, config/initializers/devise.rb, db/migrate/20191120053327_add_columns_to_users.rb, db/migrate/20191120053851_add_photo_to_users.rb, db/schema.rb
Added user firstname, lastname and avatar
=> Added user firstname, lastname and avatar

app/assets/javascripts/application.js, app/controllers/trips_controller.rb, app/views/trips/index.html.erb
Please approve this pull request about the tabs of the trips index
=> Trips Index creation with tabs

app/models/trip.rb, db/migrate/20191120083526_add_photo_to_trips.rb, db/schema.rb
=> Adding photo to Trips

app/javascript/packs/application.js, app/javascript/plugins/init_autocomplete.js, app/views/items/new.html.erb, package.json, yarn.lock
Added algolia places in new form for item (address field)
=> Added algolia places

app/models/item.rb, app/views/items/index.html.erb, app/views/items/new.html.erb, db/schema.rb, db/seeds.rb
Added collections for rating, time of day and weather.
=> Collection changes

app/javascript/packs/application.js, app/javascript/plugins/init_sweetalert.js, app/views/items/new.html.erb, db/schema.rb
Please approve this pull request
=> sweet alert for the items creation validation

Gemfile, app/controllers/items_controller.rb, app/javascript/packs/application.js, app/models/item.rb, app/views/items/new.html.erb, db/seeds.rb
fixed country select gem showing codes instead of names
=> fixed country select gem showing codes instead of names

app/models/trip.rb
Adding logic for random photo to trips
=> Adding logic for random photo to trips

app/assets/stylesheets/components/_navbar.scss, app/views/shared/_navbar.html.erb
=> Changed position of dropdown

app/views/trips/index.html.erb
Please approve this pull request
=> put card on the top

app/javascript/packs/map.js, app/javascript/plugins/autocomplete.js, app/javascript/plugins/init_autocomplete.js, app/views/items/new.html.erb, app/views/layouts/application.html.erb, app/views/shared/_map.html.erb, config/initializers/geocoder.rb, db/seeds.rb, package.json, yarn.lock
Added logic for autocomplete in address using Google Maps
=> Added logic for autocomplete in address using Google Maps

app/views/items/new.html.erb, app/views/trips/new.html.erb
change item form and add optional categories
=> change create item form

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_scrolling_country_item.scss, app/controllers/trips_controller.rb, app/javascript/packs/application.js, app/javascript/plugins/dropsubmit.js, app/views/items/_trip_card.html.erb, app/views/items/_trip_card_modal.html.erb, app/views/trips/show.html.erb
created a scroll for the country items, and a dropdown filter that automatically refreshes the page but does not loose other information that has been filtered in the trip items section. did the same for trip items. missing map.
=> Show html done

Gemfile, Gemfile.lock, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_index.scss, app/controllers/application_controller.rb, app/controllers/items_controller.rb, app/javascript/packs/map.js, app/views/items/_suggestioncard.html.erb, app/views/items/suggestions.html.erb, app/views/shared/_navbar.html.erb, config/routes.rb
Added suggestions page with data from the API. Also, now displaying Google maps
=> Added suggestions page

app/controllers/items_controller.rb, app/javascript/packs/application.js, app/javascript/plugins/init_select2.js, app/views/items/_suggestioncard.html.erb, app/views/items/_suggestioncard_modal.html.erb, app/views/items/new.html.erb, app/views/trips/new.html.erb, package.json, yarn.lock
Added select2 to forms and changed suggestions to handle no image
=> Added select2 to forms and changed suggestions to handle no image

app/views/trips/_trip.html.erb, app/views/trips/index.html.erb
Added links for the trips index page
=> Added links for the trips index page

Gemfile, Gemfile.lock, app/controllers/items_controller.rb, app/views/items/_suggestioncard_modal.html.erb, app/views/items/suggestions.html.erb
Adding from suggestions page to bucket list
=> Adding from suggestions page to bucket list

app/views/pages/home.html.erb
=> Text for landing page

app/controllers/items_controller.rb, app/views/items/_suggestioncard_modal.html.erb
Country code fix for suggestions
=> Country code

app/views/items/new.html.erb
=> Removed select2 on country

app/controllers/items_controller.rb, app/models/item.rb, app/views/items/_suggestioncard_modal.html.erb
Added logic for adding latitude and longitude
=> Added logic for adding latitude and longitude

app/views/items/_card_modal.html.erb
=> Small fixess

app/controllers/trip_items_controller.rb, app/controllers/trips_controller.rb, app/models/trip_item.rb
fixed the date dropdown, deleting an item, the flash alert, reordering, adding a date to an item on the All page, and adding an item to a specific day
=> bugs on show page - see comments

app/controllers/items_controller.rb, app/views/items/index.html.erb
Changes to fix items index page on filtering by country.
=> Changes to fix items index page

app/javascript/plugins/autocomplete.js
Changed autocomplete results for new item creation. Now showing more places
=> Changed autocomplete results

app/views/shared/_navbar.html.erb
=> Added default avatar

app/views/layouts/application.html.erb
=> Added favicon

app/controllers/application_controller.rb, app/helpers/meta_tags_helper.rb, app/views/layouts/application.html.erb, config/initializers/default_meta.rb, config/meta.yml
=> Added meta tags
